# -*- coding: utf-8 -*-
"""Working with RDF in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MuSecKh-zTYnAHJhMc5cN20Fr-NRxs9S
"""

!pip install rdflib

import rdflib

#initialize a graph
g = rdflib.Graph()

#parse through the rdf graph
result = g.parse('http://dbpedia.org/resource/Satoshi_Nakamoto')

print(len(result))

print(g.serialize(format = 'ttl'))

#loop each triple
for s,p,o in g:
  print(s,p,o)

from rdflib.namespace import RDF, RDFS, FOAF
for person in g.subjects(RDF.type, FOAF.Person):
  for ent in g.objects(person, RDFS.label):
    if(ent.language == 'en'):
      print(person)

